### index method
GET http://localhost:3000/api/events

### Successfully create an event
POST http://localhost:3000/api/events
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Mzk1MjQ5MDcsInN1YiI6NH0.NqOs9apCyfIyY5bRSqERvC3o7cg6ldvrMXHfupC3ZqQ

{
    "name": "Authorization testing",
    "description": "serious event",
    "date": "20/12/2021",
    "attendees": 30,
    "location": "Brisbane City",
    "time": "2.30pm",
    "contact_name": "Johnny1",
    "contact_phone": 111111 
}

### Unsuccessfully post an event
POST http://localhost:3000/api/events
content-type: application/json

{
    "name": "wedding",
    "description": "happy event",
    "date": "20/12/2020",
    "attendees": 20,
    "location": "Brisbane City",
    "time": "2.30pm",
    "contact_name": "Johnny"
}

### Show event id: 
GET http://localhost:3000/api/events/2

### Unsuccessfully find event id: 
GET http://localhost:3000/api/events/10

### Successfully update event 1
PUT http://localhost:3000/api/events/1
content-type: application/json


{
    "name": "Vivian",
    "attendees": 200
}

### Successfully delete event with ID 1
DELETE http://localhost:3000/api/events/1

### unsuccessfully delete event with ID 1000
DELETE http://localhost:3000/api/events/1000




### Testing User requests
#Create user
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "email": "johnny1@test.com",
    "password": "111111",
    "password_confirmation": "111111",
    "first_name": "johnny1",
    "last_name": "Nguyen1",
    "phone": 111111    
}

### Sign in with correct details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{
    "email": "johnny@test.com",
    "password": "password1"
}

